### ISSUE TITLE
Profanity filter and bad behaviour tracking

### ISSUE THREAD

**Issue by diguifi** [tiny-devs/tiny-dungeon-online#121]
Why would someone join such tiny independent game to be mean to people online? I don't know, but they made this issue necessary.

- [ ] Filter client side
- [x] Server side bad behaviour count for players
- [ ] maybe an IP ban system? Account reset?
